#!/bin/sh

scrape=$PWD/scrape
blacklist=$PWD/../blacklist

mkdir -p sites

mkdir -p sites/alpha/
cp ../seed sites/alpha/input

cd sites/alpha
while read site; do
  $scrape -n 30 $site
done < input
cd ../../

mkdir -p sites/beta/
cat sites/alpha/*_other | sort | uniq | grep -v -f $blacklist > sites/beta/input

cd sites/beta
while read site; do
  $scrape -n 10 $site
done < input
cd ../../


